### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by arranf** [picnicss/picnic#105]
By default the nav is fixed to the top on scroll, it'd be great to have a single class that stops that.

**Comment by franciscop** [comment]
I am sorry but Picnic's scope is not to add a class for everything; it is to provide a good foundation so you can build your own parts. You can do this if you want to stop it from scrolling:

```css
nav {
  position: absolute;
}
```

Or this:

```css
nav {
  position: relative;
}
```

or even this:

```css
nav {
  position: static;
}
```
