### ISSUE TITLE
Feature Request: Outline button

### ISSUE THREAD

**Issue by Immortalin** [picnicss/picnic#116]
Can you add a button similar to the [Outline Button](http://usewing.ml/) in Wing?

**Comment by franciscop** [comment]
Hi @Immortalin , unfortunately I don't think it's a good idea to add it to the Picnic code; you can easily [recreate it with](https://jsfiddle.net/franciscop/07u46z6o/1/):

```css
button.outline,
.button.outline {
  background: none;
  border: 3px solid #fff;
  transition: all .1s ease;
}

button.outline:hover,
.button.outline:hover {
  color: #000;
  box-shadow: 0 0 100em #fff inset;
}

button.outline:active,
.button.outline:active {
  color: #000;
  transform: scale(0.9);
  box-shadow: 0 0 100em #fff inset;
}
```
