### ISSUE TITLE
Pure-CSS Float Label

### ISSUE THREAD

**Issue by tonystar** [picnicss/picnic#122]
A good addition to the Picnic CSS will be a pure-CSS Float Labels:
https://github.com/tonystar/float-label-css!

**Comment by franciscop** [comment]
Hi @tonystar . I love that style but I think it's too prescriptive for Picnic and that it would make labels difficult to change. Picnic's objectives are twofold:

1. Giving nice defaults
2. Making it easy to extend it

While it's great for the first one, I think it works against the last one. Thanks for the suggestion though.

**Comment by tonystar** [comment]
@franciscop don't agree. The ky difference of my solution is to be semantically correct.

I don't use any "hacks" and rely on `:placeholder-shown`.

Customization is also pretty simple using semantic mixins.

Look how I did for Bootstrap:
```scss
.has-float-label {
  @include float-label-container;

  @include float-label {
    top: -.5em;
    left: $input-padding-x;
    z-index: 3;
    line-height: 1;
    padding: 0 1px;

  .form-control {
    @include float-label-input;

    @include float-label-scaled {
      top: .3em;
    }
  }
}
```

https://github.com/tonystar/bootstrap-float-label/blob/master/scss/_float-label.scss
