### ISSUE TITLE
padding-right on td and th very large

### ISSUE THREAD

**Issue by abumalick** [picnicss/picnic#123]
Hello,
thanks for your library it is very pretty and useful

I found that padding right on td and th was very large (2.4em), I don' t know why, I have changed to 0.

in _plugin.scss
``` scss
td,
th {
  padding: $picnic-separation / 2 2.4em $picnic-separation / 2 $picnic-separation;
  }
```

keep up the good work 👍
